# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
cache: packages

sudo: true

dist: bionic
addons:
  apt:
    packages:
      - python3-venv
      - python3-pip
      - python3-setuptools

r_binary_packages:
  - reticulate
  - tensorflow

install:
  - python3 -m pip -q install --upgrade pip setuptools
  - python3 -m pip install tensorflow


git:
  quiet: true
  depth: 3

