# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: true


# https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb
# https://github.com/rstudio/keras/blob/master/.github/workflows/main.yaml
#


language: r

# dist: bionic
addons:
  apt:
    packages:
      - python3-pip
      # - python3-venv
      # - python3-setuptools


before_install:
  - python3 -m pip -q install --upgrade pip setuptools
  - python3 -m pip -q install tensorflow

r_binary_packages:
  - reticulate
  - tensorflow
  - testthat
  - remotes

install:
  - Rscript -e "remotes::install_deps()"

# suppress log size
git:
  quiet: true
  depth: 3
